# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1158, 795)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.comb_algorithm = QtWidgets.QComboBox(Form)
        self.comb_algorithm.setObjectName("comb_algorithm")
        self.comb_algorithm.addItem("")
        self.comb_algorithm.addItem("")
        self.comb_algorithm.addItem("")
        self.horizontalLayout_2.addWidget(self.comb_algorithm)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.comb_size = QtWidgets.QComboBox(Form)
        self.comb_size.setObjectName("comb_size")
        self.horizontalLayout_2.addWidget(self.comb_size)
        self.btn_start = QtWidgets.QPushButton(Form)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_2.addWidget(self.btn_start)
        self.btn_stop = QtWidgets.QPushButton(Form)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_2.addWidget(self.btn_stop)
        self.btn_clrear = QtWidgets.QPushButton(Form)
        self.btn_clrear.setObjectName("btn_clrear")
        self.horizontalLayout_2.addWidget(self.btn_clrear)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.group_box_firgure = QtWidgets.QGroupBox(Form)
        self.group_box_firgure.setObjectName("group_box_firgure")
        self.verticalLayout.addWidget(self.group_box_firgure)
        self.progress_bar = QtWidgets.QProgressBar(Form)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setTextVisible(True)
        self.progress_bar.setOrientation(QtCore.Qt.Horizontal)
        self.progress_bar.setInvertedAppearance(False)
        self.progress_bar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.group_box_info = QtWidgets.QGroupBox(Form)
        self.group_box_info.setObjectName("group_box_info")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_box_info)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.group_box_cpu = QtWidgets.QGroupBox(self.group_box_info)
        self.group_box_cpu.setObjectName("group_box_cpu")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.group_box_cpu)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.group_box_cpu)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_my_cpu = QtWidgets.QLabel(self.group_box_cpu)
        self.label_my_cpu.setObjectName("label_my_cpu")
        self.gridLayout_6.addWidget(self.label_my_cpu, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.group_box_cpu)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_dataset_name = QtWidgets.QLabel(self.group_box_cpu)
        self.label_dataset_name.setWordWrap(True)
        self.label_dataset_name.setObjectName("label_dataset_name")
        self.gridLayout_6.addWidget(self.label_dataset_name, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.group_box_cpu)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_my_ram = QtWidgets.QLabel(self.group_box_cpu)
        self.label_my_ram.setObjectName("label_my_ram")
        self.gridLayout_6.addWidget(self.label_my_ram, 2, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.group_box_cpu, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.group_box_info)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.group_box_ram = QtWidgets.QGroupBox(self.group_box_info)
        self.group_box_ram.setObjectName("group_box_ram")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_box_ram)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.group_box_ram)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_time = QtWidgets.QLabel(self.group_box_ram)
        self.label_time.setObjectName("label_time")
        self.horizontalLayout_3.addWidget(self.label_time)
        self.horizontalLayout_3.setStretch(1, 1)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.group_box_ram, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.group_box_info)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_freq = QtWidgets.QLabel(self.groupBox)
        self.label_freq.setObjectName("label_freq")
        self.gridLayout.addWidget(self.label_freq, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_ram = QtWidgets.QLabel(self.groupBox)
        self.label_ram.setObjectName("label_ram")
        self.gridLayout.addWidget(self.label_ram, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_cpu_load = QtWidgets.QLabel(self.groupBox)
        self.label_cpu_load.setObjectName("label_cpu_load")
        self.gridLayout.addWidget(self.label_cpu_load, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.group_box_info)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_4.addWidget(self.lineEdit_2)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_4.addWidget(self.lineEdit_3)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        self.gridLayout_2.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.group_box_info)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Algorithm:"))
        self.comb_algorithm.setItemText(0, _translate("Form", "New Item"))
        self.comb_algorithm.setItemText(1, _translate("Form", "New Item"))
        self.comb_algorithm.setItemText(2, _translate("Form", "New Item"))
        self.label_9.setText(_translate("Form", "Sample Size:"))
        self.btn_start.setText(_translate("Form", "Start"))
        self.btn_stop.setText(_translate("Form", "Stop"))
        self.btn_clrear.setText(_translate("Form", "Clear"))
        self.group_box_firgure.setTitle(_translate("Form", "Plot Area"))
        self.progress_bar.setFormat(_translate("Form", "%p%"))
        self.group_box_info.setTitle(_translate("Form", "Statics"))
        self.group_box_cpu.setTitle(_translate("Form", "Compute Consume"))
        self.label_4.setText(_translate("Form", "DataSet:"))
        self.label_my_cpu.setText(_translate("Form", "0%"))
        self.label_6.setText(_translate("Form", "CPU Usage:"))
        self.label_dataset_name.setText(_translate("Form", "csv_file_name"))
        self.label_8.setText(_translate("Form", "Ram Usage:"))
        self.label_my_ram.setText(_translate("Form", "0MB"))
        self.pushButton.setText(_translate("Form", "Clear "))
        self.group_box_ram.setTitle(_translate("Form", "Running Time"))
        self.label_3.setText(_translate("Form", "Time:"))
        self.label_time.setText(_translate("Form", "00:00:01"))
        self.groupBox.setTitle(_translate("Form", "System Info"))
        self.label_2.setText(_translate("Form", "RAM:"))
        self.label_freq.setText(_translate("Form", "81%"))
        self.label.setText(_translate("Form", "CPU Freq:"))
        self.label_ram.setText(_translate("Form", "18M"))
        self.label_5.setText(_translate("Form", "CPU Load:"))
        self.label_cpu_load.setText(_translate("Form", "10%"))
        self.groupBox_2.setTitle(_translate("Form", "Parameters"))
        self.label_10.setText(_translate("Form", "sample_layout_iterations:"))
        self.label_11.setText(_translate("Form", "remainder_layout_iterations:"))
        self.label_12.setText(_translate("Form", "refine_layout_iterations:"))
        self.label_13.setText(_translate("Form", "random_sample_size:"))
